### ISSUE TITLE
Please add pip format requirements.txt

### ISSUE THREAD

**Issue by LZ-Dong** [YichenZW/Coh-MGT-Detection#1]
When I configure the environment, ```conda create --name coco --file requirements.txt``` goes wrong. I think a pip format requirements.txt would be helpful.
![image](https://github.com/YichenZW/Coh-MGT-Detection/assets/104953644/ee82881a-9e63-46ff-b517-239f2be54b55)

**Comment by YichenZW** [comment]
Thank you for pointing out! Here is the pip version:
[requirements.txt](https://github.com/YichenZW/Coh-MGT-Detection/files/13973421/requirements.txt)
I hope it helps!

**Comment by LZ-Dong** [comment]
Thanks a lot for your reply!

**Comment by wangzihang33** [comment]
您给的pip版本的包版本互相冲突
![微信图片_20250110205412](https://github.com/user-attachments/assets/2e6816a6-553d-4fdf-89a6-5822d5437e16)

**Comment by wangzihang33** [comment]
torchaudio 2.0.2+cu118 版本所要求的 torch 版本又为（2.0.1）
