### ISSUE TITLE
Where is the **_Graph.jsonl ? 

### ISSUE THREAD

**Issue by shallow777** [YichenZW/Coh-MGT-Detection#2]
In the dataset, i don't find the **_Graph.jsonl. But i find the problem in the picture.  How can i solve the problem? Thanks for your reply.
[微信截图_20240129175640](https://github.com/YichenZW/Coh-MGT-Detection/assets/119467390/e4e2a0c7-23d0-4b86-b59e-a8dc1ed84cc8)

**Comment by shallow777** [comment]
In the dataset, i only have these.
[image](https://github.com/YichenZW/Coh-MGT-Detection/assets/119467390/3a411d5a-cf6a-4fb0-a933-159d060a4bd5)

**Comment by YichenZW** [comment]
Hi, shallow777. Sorry for the confusion. You need to run preprocess/extract_keywords.py and then preprocess/construct_graph.py
 to bulid the graph. I think this part is still marked as [TBD] so I'll finish it asap. Thank you for your interests!

**Comment by shallow777** [comment]
Thanks a lot for your reply!
